
namespace IncomeExpenditureTracker.Models
{
    /// <summary>
    /// A universal container for any piece of metadata or column structure detected in an Excel statement.
    /// Acts as the single unit of data exchange between Extractor, Edit Session, and Import Service.
    /// </summary>
    public class DetectedField
    {
        /// <summary>
        /// The standardized domain concept this field represents
        /// (e.g., "Date", "Description", "AccountNumber", "EntityName").
        /// </summary>
        public string SuggestedField { get; set; } = "";

        /// <summary>
        /// The raw text found in the Excel cell (e.g., "TXN_DT", "A/C NO:", "PARTICULARS").
        /// Essential for triggering SynonymService.LearnFromCorrectionAsync() upon confirmation.
        /// </summary>
        public string ColumnName { get; set; } = "";

        /// <summary>
        /// 0-BASED INDEXING: 0 is the first column. -1 indicates "Not Detected".
        /// Primarily used for Transaction Columns (Date, Amount, Description).
        /// Defaults to -1 if undetected or not applicable.
        /// </summary>
        public int ColumnIndex { get; set; } = -1;

        /// <summary>
        /// The actual string value extracted from the sheet.
        /// Primarily used for Account and Entity metadata (e.g., "1234-5678", "HDFC Bank", "INR").
        /// </summary>
        public string ExtractedValue { get; set; } = "";

        /// <summary>
        /// The Levenshtein similarity score (0.0 to 1.0) generated by the matching engine.
        /// Useful for the UI to display warning badges on low-confidence detections.
        /// </summary>
        public double ConfidenceScore { get; set; }

        /// <summary>
        /// Indicates whether the user explicitly modified or confirmed this field during the edit session.
        /// </summary>
        public bool IsUserVerified { get; set; }

        /// <summary>
        /// Helper property to quickly check if the extractor actually found this field.
        /// </summary>
        public bool IsDetected => ColumnIndex >= 0 || !string.IsNullOrWhiteSpace(ExtractedValue);
    }
}