using System;
using System.Collections.Generic;
using System.Linq;
using IncomeExpenditureTracker.Models;
using Microsoft.Extensions.Logging;

namespace IncomeExpenditureTracker.Services.StatementManagement
{
    /// <summary>
    /// Acts as the in-memory staging area (the "workbench") during the 20-row verification step.
    /// It isolates user UI experimentation from the database until explicit confirmation.
    /// </summary>
    public class StatementEditSession : IStatementEditSession
    {
        private readonly ILogger<StatementEditSession> _logger;

        // Holds the active 20-row sample preview currently being displayed in the Avalonia UI.
        private StatementPreview? _currentPreview;

        // An internal scratchpad that records every time the user fixes a column mapping.
        // We keep this private so only this service can manage how corrections are logged.
        private readonly List<ColumnMappingCorrection> _columnCorrections = new();

        public StatementEditSession(ILogger<StatementEditSession> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Step 1: Seeds the session with the initial preview generated by ExcelStatementExtractor.
        /// Called by StatementManager immediately before navigating the user to the verification screen.
        /// </summary>
        public void Initialize(StatementPreview preview)
        {
            // Guard clause: Ensure we don't accidentally initialize with a null object.
            if (preview == null)
            {
                _logger.LogError("StatementEditSession initialization rejected: preview argument was null.");
                throw new ArgumentNullException(nameof(preview));
            }

            _currentPreview = preview;

            _logger.LogInformation(
                "Initialized statement edit session with preview containing {FieldCount} detected fields and {TransactionCount} sample transactions.",
                _currentPreview.Fields?.Count ?? 0,
                _currentPreview.PreviewTransactions?.Count ?? 0);

            // If the user previously imported another statement in the same app session,
            // we wipe the old correction scratchpad clean so old corrections don't bleed over.
            _columnCorrections.Clear();
            _logger.LogDebug("Cleared previous column mapping corrections before starting a new preview session.");
        }

        /// <summary>
        /// Step 2: Provides the live preview object to the presentation layer.
        /// Your Avalonia ViewModel will bind its DataGrid directly to this object.
        /// </summary>
        public StatementPreview GetCurrentPreview()
        {
            // Prevent UI crashes by ensuring StatementManager actually called Initialize() first.
            EnsureInitialized();
            return _currentPreview!;
        }

        /// <summary>
        /// Step 3 & 4: Called whenever the user changes a column header dropdown in the UI.
        /// Example: User maps Column Index 1 (with raw text "PARTICULARS") to "Description".
        /// </summary>
        /// <param name="targetField">The standard domain field (e.g., "Description", "Date").</param>
        /// <param name="rawHeaderName">The weird header text from Excel (e.g., "PARTICULARS").</param>
        /// <param name="newColumnIndex">The zero-based Excel column number selected by the user.</param>
        /// <param name="category">The category of the statement (e.g., "TRANSACTION", "METADATA", etc.).</param>
        public void UpdateColumnMapping(string targetField, string rawHeaderName, int newColumnIndex, string category)
        {
            EnsureInitialized();

            if (string.IsNullOrWhiteSpace(targetField))
            {
                _logger.LogError("Column mapping rejected: target field was empty or whitespace. Raw header: '{RawHeaderName}', category: '{Category}', column index: {ColumnIndex}.",
                    rawHeaderName,
                    category,
                    newColumnIndex);
                throw new ArgumentException("Target field cannot be empty.", nameof(targetField));
            }

            // DEFENSIVE GUARD FOR 0-BASED INDEXING:
            // 0 is now a valid column (Column A). Only negative numbers are invalid.
            // (Note: If your UI explicitly passes -1 to mean "Unmap this column", change this check to: newColumnIndex < -1)
            if (newColumnIndex < 0)
            {
                _logger.LogError("Column mapping rejected for target field '{TargetField}': invalid column index {ColumnIndex}. Raw header: '{RawHeaderName}', category: '{Category}'.",
                    targetField,
                    newColumnIndex,
                    rawHeaderName,
                    category);
                throw new ArgumentOutOfRangeException(nameof(newColumnIndex), "Column index must be 0 or greater in a zero-based system.");
            }

            _logger.LogInformation(
                "Applying manual column mapping for '{TargetField}' from raw header '{RawHeaderName}' to column index {ColumnIndex} under category '{Category}'.",
                targetField,
                rawHeaderName,
                newColumnIndex,
                category);

            // ACTION 1: Mutate the live preview immediately.
            // Because the Avalonia UI is bound to _currentPreview, changing the index here
            // causes the UI DataGrid to instantly rearrange and show the correct column data.
            // ApplyMappingToPreview(targetField, rawHeaderName, newColumnIndex);

            // 1. Update the live preview dictionary to reflect the user's choice
            if (_currentPreview!.Fields.TryGetValue(targetField, out var existingField))
            {
                existingField.ColumnIndex = newColumnIndex;
                existingField.ColumnName = rawHeaderName;
                // Optionally reset confidence to 100 since the user manually verified it
                existingField.ConfidenceScore = 100;
                existingField.IsUserVerified = true;
                _logger.LogDebug("Updated existing preview mapping for field '{TargetField}' to column {ColumnIndex}.", targetField, newColumnIndex);
            }
            else
            {
                // If the field wasn't mapped at all initially, add it to the dynamic dictionary
                _currentPreview.Fields[targetField] = new DetectedField
                {
                    ColumnIndex = newColumnIndex,
                    ColumnName = rawHeaderName,
                    ConfidenceScore = 100, // User verified
                    IsUserVerified = true
                };
                _logger.LogDebug("Added new preview mapping for field '{TargetField}' to column {ColumnIndex}.", targetField, newColumnIndex);
            }

            // ACTION 2: Record this change in our correction scratchpad so SynonymService
            // can learn from it LATER (only if the user actually clicks Confirm).
            TrackCorrection(targetField, rawHeaderName, newColumnIndex, category);
        }

        /// <summary>
        /// Step 5: Called when the user clicks the "Confirm & Import" button in the UI.
        /// Packages the finalized preview and the deduplicated learning instructions.
        /// </summary>
        public PreviewTracker ConfirmAndPrepareForImport()
        {
            EnsureInitialized();

            var correctionCount = _columnCorrections.Count;
            _logger.LogInformation(
                "Confirming statement edit session and preparing import. Final preview field count: {FieldCount}, pending corrections: {CorrectionCount}.",
                _currentPreview!.Fields?.Count ?? 0,
                correctionCount);

            // Create the final output package for StatementManager
            var tracker = new PreviewTracker
            {
                // The cleaned-up 20-row sample with all user column corrections applied
                FinalPreview = _currentPreview!,

                // We create a new List copy (a snapshot) of our corrections.
                // This prevents external code from accidentally modifying our internal state.
                ColumnCorrections = [.. _columnCorrections]
            };

            return tracker;
        }

        /// <summary>
        /// Step 6: Cleans up memory. Called by StatementManager after the import finishes
        /// or if the user clicks "Cancel" on the verification screen.
        /// </summary>
        public void Clear()
        {
            _currentPreview = null;
            _columnCorrections.Clear();
        }

        #region Private Helper Methods

        /// <summary>
        /// Safety check to enforce strict workflow order: Loader -> Extractor -> EditSession.
        /// </summary>
        private void EnsureInitialized()
        {
            if (_currentPreview == null)
            {
                _logger.LogError("StatementEditSession was used before it was initialized. Call Initialize() first.");
                throw new InvalidOperationException(
                    "StatementEditSession has not been initialized with a preview. Call Initialize() first.");
            }
        }

        /// <summary>
        /// Implements "Smart Deduplication". If a user clicks around and changes the same column
        /// multiple times, we only want to remember their FINAL choice.
        /// </summary>
        private void TrackCorrection(string targetField, string rawHeaderName, int newColumnIndex, string category)
        {
            // Look into our scratchpad: Did the user ALREADY change this specific field during this session?
            // Example: Did they already try to map something to "Description" 5 seconds ago?
            var existingCorrection = _columnCorrections
                .FirstOrDefault(c => c.TargetField.Equals(targetField, StringComparison.OrdinalIgnoreCase)
                                    && c.Category.Equals(category, StringComparison.OrdinalIgnoreCase));

            if (existingCorrection != null)
            {
                // DEDUPLICATION: Instead of adding a second entry, we just overwrite the existing one.
                // If they mapped Column 2 to Description, but now chose Column 1, we update it to Column 1.
                existingCorrection.RawHeaderName = rawHeaderName;
                existingCorrection.NewColumnIndex = newColumnIndex;
                _logger.LogDebug(
                    "Updated deduplicated correction for target '{TargetField}' in category '{Category}' to raw header '{RawHeaderName}' at column {ColumnIndex}.",
                    targetField,
                    category,
                    rawHeaderName,
                    newColumnIndex);
            }
            else
            {
                // First time the user is correcting this specific field in this session. Add a new note.
                _columnCorrections.Add(new ColumnMappingCorrection
                {
                    TargetField = targetField,
                    RawHeaderName = rawHeaderName,
                    NewColumnIndex = newColumnIndex,
                    Category = category
                });
                _logger.LogDebug(
                    "Recorded new correction for target '{TargetField}' in category '{Category}' mapping to raw header '{RawHeaderName}' at column {ColumnIndex}.",
                    targetField,
                    category,
                    rawHeaderName,
                    newColumnIndex);
            }
        }

        #endregion
    }
}