using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using IncomeExpenditureTracker.Models;


namespace IncomeExpenditureTracker.Services.Tagging;

// ------------------------------------------------------------
// TAG ENGINE
// ------------------------------------------------------------
// This engine assigns a TagId to each transaction.
//
// Input:
// - Transaction list
// - Token list (generated by DescriptionParser)
//
// Output:
// - Transaction.TagId populated
//
// Design Goals:
// - Fast processing
// - Parallel execution
// - Rule priority support
// - Safe error handling
//
// Important:
// TagEngine does NOT talk to the database.
// It reads rules from RuleBook which keeps them in memory.
// ------------------------------------------------------------
public class TagEngine
{
    private readonly RuleBook _ruleBook;

    public TagEngine(RuleBook ruleBook)
    {
        _ruleBook = ruleBook;
    }

    // ------------------------------------------------------------
    // PROCESS TRANSACTIONS
    // ------------------------------------------------------------
    // This method assigns tags to all transactions.
    //
    // transactions → rows to classify
    // tokenRows    → tokens extracted from each description
    //
    // tokenRows[i] corresponds to transactions[i]
    // ------------------------------------------------------------
    public async Task ProcessTransactions(List<Transaction> transactions, List<List<string>> tokenRows)
    {
        try
        {
            if (transactions == null || tokenRows == null)
                throw new ArgumentNullException("Transactions or tokenRows cannot be null.");

            if (transactions.Count != tokenRows.Count)
                throw new Exception("Transaction count does not match token row count.");

            var ruleIndex = await _ruleBook.GetRuleIndexAsync();

            if (ruleIndex == null || ruleIndex.Count == 0)
                throw new Exception("RuleBook is empty. Rules must be loaded before tagging.");

            // Fallback tag used when no rule matches
            var miscTagId = await _ruleBook.GetMiscTagIdAsync();

            // ------------------------------------------------------------
            // PARALLEL ROW PROCESSING
            // ------------------------------------------------------------
            // Each row is independent so we process them in parallel
            // to utilize multiple CPU cores.
            // ------------------------------------------------------------
            Parallel.For(0, transactions.Count, i =>
            {
                var transaction = transactions[i];
                var tokens = tokenRows[i];

                try
                {
                    if (transaction == null)
                        return;

                    // ----------------------------------------------------
                    // SKIP ALREADY TAGGED ROWS
                    // ----------------------------------------------------
                    // If the user manually tagged a transaction,
                    // we should not override it.
                    // ----------------------------------------------------
                    if (transaction.TagId != null)
                        return;

                    int bestPriority = -1;
                    int? bestTag = null;

                    // ----------------------------------------------------
                    // TOKEN MATCHING
                    // ----------------------------------------------------
                    // For each token we check if a rule exists.
                    //
                    // If multiple rules match:
                    // The rule with the highest priority wins.
                    // ----------------------------------------------------

                    // Guard against null tokens
                    if (tokens != null)
                    {
                        foreach (var token in tokens)
                        {
                            if (string.IsNullOrWhiteSpace(token))
                                continue;

                            // ruleIndex is a dictionary where:
                            // key = token (uppercased)
                            // value = list of rules that match this token
                            // We check if there are any rules for this token, and if so, we evaluate their priority.

                            if (ruleIndex.TryGetValue(token, out var rules))
                            {
                                // If multiple rules match the same token, we need to determine which one has the highest priority.
                                // This allows us to support complex scenarios where multiple tags could apply, and we want to ensure the most important one is chosen.
                                // For example, if we have a token "GROCERY" that matches both "Food" and "Essentials" tags, we can assign different priorities to these rules in the database.
                                // During tagging, if both rules match, we will assign the tag with the higher priority to ensure consistent classification.
                                foreach (var rule in rules)
                                {
                                    if (rule.Priority > bestPriority)
                                    {
                                        bestPriority = rule.Priority;
                                        bestTag = rule.TagId;
                                    }
                                }
                            }
                        }
                    }

                    // ----------------------------------------------------
                    // ASSIGN TAG
                    // ----------------------------------------------------
                    // If no rule matched, assign fallback tag (Misc)
                    // ----------------------------------------------------
                    transaction.TagId = bestTag ?? miscTagId;
                }
                catch (Exception ex)
                {
                    // ----------------------------------------------------
                    // ROW LEVEL ERROR HANDLING
                    // ----------------------------------------------------
                    // Instead of stopping the entire tagging process,
                    // we mark the row so the user can investigate later.
                    // ----------------------------------------------------
                    transaction.Entity = "ERROR: " + ex.Message;

                    // Assign fallback tag to keep data consistent
                    transaction.TagId = miscTagId;
                }
            });
        }
        catch (Exception ex)
        {
            // ------------------------------------------------------------
            // CRITICAL TAGGING FAILURE
            // ------------------------------------------------------------
            // If this fails, something is wrong with the pipeline
            // (RuleBook not loaded, mismatched token rows, etc.)
            // ------------------------------------------------------------
            Console.WriteLine($"[TagEngine] Processing failed: {ex.Message}");
            throw;
        }
    }
}